services:
  rag_chatbot:
    build: .
    ports:
      - "5000:5000"
      - "11434:11434"
    volumes:
      - ollama_data:/home/rag_user/.ollama
      - ./chat_history:/app/chat_history
      - ${FIREBOLT_RAG_CHATBOT_LOCAL_GITHUB_PATH}:/github
      - .:/app
    environment:
      - FIREBOLT_RAG_CHATBOT_ENGINE=${FIREBOLT_RAG_CHATBOT_ENGINE}
      - FIREBOLT_RAG_CHATBOT_DB=${FIREBOLT_RAG_CHATBOT_DB}
      - FIREBOLT_RAG_CHATBOT_CLIENT_ID=${FIREBOLT_RAG_CHATBOT_CLIENT_ID}
      - FIREBOLT_RAG_CHATBOT_CLIENT_SECRET=${FIREBOLT_RAG_CHATBOT_CLIENT_SECRET}
      - FIREBOLT_RAG_CHATBOT_ACCOUNT_NAME=${FIREBOLT_RAG_CHATBOT_ACCOUNT_NAME}
      - FIREBOLT_RAG_CHATBOT_TABLE_NAME=${FIREBOLT_RAG_CHATBOT_TABLE_NAME}
      - FIREBOLT_RAG_CHATBOT_LOCAL_GITHUB_PATH=${FIREBOLT_RAG_CHATBOT_LOCAL_GITHUB_PATH}
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  ollama_data:
    driver: local
